version: '3.7'

services:
  dem_backend:
    image: 'kristjangrm/nifty-links-backend:main'
    container_name: nifty-links-backend
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-10325.c100.us-east-1-4.ec2.cloud.redislabs.com
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=10325
      - JWT_SECRET=$JWT_SECRET
      - BLOCKCHAIN_URL=$BLOCKCHAIN_URL
      - APPLICATION_HOSTNAME=api.nftlink.cc
      - NFT_STORAGE_API_KEY=$NFT_STORAGE_API_KEY
      - BLOCKCHAIN_MNEMONIC_PATH=$BLOCKCHAIN_MNEMONIC_PATH
      - BLOCKCHAIN_NFT_ADDRESS=$BLOCKCHAIN_NFT_ADDRESS
    volumes:
      - ./mnemonic.txt:/mnemonic.txt
    ports:
    - "8082:8082"
